export interface Specification {
  label: string
  value: string
}

export const productSpecifications: Record<string, Specification[]> = {
  "ess-12-8v-100ah": [
    { label: "Model Name", value: "ESS12.8V100AH" },
    { label: "Specification", value: "12.8V 100AH" },
    { label: "Capacity (kwh)", value: "1.28 kWh (1280 Wh)" },
    { label: "Battery Type", value: "Lithium Iron Phosphate (LiFePO4)" },
    { label: "BMS Type", value: "Smart JBD" },
    { label: "Communication", value: "RS485" },
    { label: "Max charging current", value: "50AMP" },
    { label: "Cycle life", value: "≥ 4000 Cycles @ 80% DoD" },
    { label: "Depth of Discharge (DOD)", value: "95%" },
    { label: "Charging Temperature", value: "0°C to 55°C" },
    { label: "Discharging Temperature", value: "-20°C to 60°C" },
    { label: "Operating Voltage Range", value: "10.0V – 14.6V" },
    { label: "Discharge Cut-off Voltage", value: "10.0V" },
    { label: "Peak Discharge Current", value: "200A (10 sec)" },
    { label: "Storage Temperature", value: "0°C to 35°C" },
    { label: "Design Life", value: "10+ Years" },
    { label: "Warranty", value: "Up to 5 Years" }
  ],
  "ess-25-6v-105ah": [
    { label: "Model Name", value: "ESS25.6V105AH" },
    { label: "Specification", value: "25.6V 105AH" },
    { label: "Capacity (kwh)", value: "2.69 kWh (2688 Wh)" },
    { label: "Battery Type", value: "Lithium Iron Phosphate (LiFePO4)" },
    { label: "Communication", value: "BT" },
    { label: "Max charging current", value: "50 AMP" },
    { label: "Cycle Life", value: "≥ 4000 Cycles @ 80% DoD" },
    { label: "Depth of Discharge (DOD)", value: "95%" },
    { label: "Operating Voltage Range", value: "21.6V – 29.2V" },
    { label: "Charge Voltage", value: "28.8V" },
    { label: "BMS", value: "Intelligent Built-in BMS" },
    { label: "Charging Temperature", value: "0°C to 55°C" },
    { label: "Installation", value: "Wall Mount / Floor Standing" },
    { label: "Warranty", value: "Up to 5 Years" }
  ],
  "ess-25-6v-230ah": [
    { label: "Model Name", value: "ESS25.6V230AH" },
    { label: "Specification", value: "25.6V / 230Ah" },
    { label: "Capacity (kwh)", value: "5.88kWh" },
    { label: "BMS Type", value: "Smart" },
    { label: "Max charging current", value: "50A" },
    { label: "Cycle Life", value: "4000 (0.5C/0.5C, 70%EOL, 80%DOD, 25°C)" },
    { label: "Max. recommended DOD", value: "95%" },
    { label: "Dimension (LXWXH)", value: "732*130*370 mm" },
    { label: "Weight", value: "70kg approx" },
    { label: "Battery Type", value: "LFP" },
    { label: "Battery efficiency", value: "95%" },
    { label: "Operating temperature", value: "-10〜50℃" },
    { label: "Case Material", value: "MS" },
    { label: "Max charging Voltage", value: "29.2V" },
    { label: "Humidity", value: "5%〜95% (No condensed water)" },
    { label: "Warranty", value: "5 years" }
  ],
  "ess-48v-314ah": [
    { label: "Model Name", value: "ESS48V314AH" },
    { label: "Specification", value: "48V 314AH" },
    { label: "Capacity (kwh)", value: "15.07KWH" },
    { label: "Battery Chemistry", value: "Lithium Iron Phosphate (LiFePO4)" },
    { label: "BMS Type", value: "Smart 16S 200AMP (JBD/DALY)" },
    { label: "Communication", value: "RS485" },
    { label: "Max charging current", value: "180AMP / 200AMP" },
    { label: "Cycle Life", value: "≥ 4000 Cycles @ 80% DoD" },
    { label: "Depth of Discharge (DOD)", value: "95%" },
    { label: "Operating Voltage Range", value: "43.2V – 58.4V" },
    { label: "Charging Temperature", value: "0°C to 55°C" },
    { label: "Discharging Temperature", value: "-20°C to 60°C" },
    { label: "Storage Temperature", value: "0°C to 35°C" },
    { label: "Scalability", value: "Parallel Expansion Supported" },
    { label: "Installation", value: "Floor Standing" },
    { label: "Design Life", value: "10+ Years" },
    { label: "Warranty", value: "Up to 7 Years" }
  ],
  "ess-51-2v-105ah": [
    { label: "Model Name", value: "ESS51.2V105AH" },
    { label: "Specification", value: "51.2V 105AH" },
    { label: "Capacity (kwh)", value: "5.36 KWH / 5.37 KWH" },
    { label: "Battery type", value: "LFP" },
    { label: "BMS Type", value: "Smart JBD/PALY" },
    { label: "Communication", value: "RS485/CAN" },
    { label: "Max charging current", value: "50A(single) / 100A(multiple stack)" },
    { label: "Cycle life", value: ">=4000 @ 80% DOD" },
    { label: "Depth of Discharge (DOD)", value: "95%" },
    { label: "Nominal Capacity", value: "105Ah" },
    { label: "Operating Temperature", value: "0°C to 45°C (Charge), -20°C to 60°C (Discharge)" },
    { label: "Case Material", value: "Metal" },
    { label: "Weight", value: "Approx. 55 kg" },
    { label: "Stack Capacity", value: "5kwh / 10kwh / 15kwh / 20kwh" },
    { label: "Installation", value: "Rack Mounted / Stackable / Ground Installation" },
    { label: "Warranty", value: "5 Years (Standard) / Up to 5 Years" }
  ],
  "ess-51-2v-150ah": [
    { label: "Model Name", value: "ESS51.2V150AH" },
    { label: "Nominal Voltage", value: "51.2 V" },
    { label: "Nominal Capacity", value: "150 Ah" },
    { label: "Nominal Energy", value: "7.68 kWh" },
    { label: "Battery Chemistry", value: "LiFePO4" },
    { label: "Cell Type", value: "Prismatic" },
    { label: "Communication", value: "CAN / RS485" },
    { label: "Max Charging Current", value: "100 A / 120A(single) / 180A(multiple in parallel)" },
    { label: "Continuous Discharge Current", value: "75 A (0.5 C)" },
    { label: "Peak Discharge Current", value: "150 A (10 Seconds)" },
    { label: "Charge Voltage", value: "58.4 V" },
    { label: "Depth of Discharge", value: "95%" },
    { label: "Cycle Life", value: "≥ 4000 Cycles @ 80% DOD" },
    { label: "Operating Temperature", value: "0°C to 55°C" },
    { label: "Scalability", value: "Up to 16 Units in Parallel" },
    { label: "BMS Protection", value: "Intelligent Smart BMS / Smart JBD/PALY" },
    { label: "Warranty", value: "5 Years (Standard)" }
  ],
  "ess-51-2v-230ah": [
    { label: "Model Name", value: "ESS51.2V230AH" },
    { label: "Nominal Voltage", value: "51.2 V" },
    { label: "Nominal Capacity", value: "230 Ah" },
    { label: "Capacity (kWh)", value: "11.78 kWh" },
    { label: "Battery Chemistry", value: "LiFePO4" },
    { label: "Communication", value: "CAN / RS485" },
    { label: "Max Charging Current", value: "100 A" },
    { label: "Cycle Life @ 80% DOD", value: "≥4000 Cycles" },
    { label: "Depth of Discharge", value: "95%" },
    { label: "Continuous Discharge Current", value: "0.5 C (115 A)" },
    { label: "Discharge Current", value: "1 C (230 A, 10 Seconds)" },
    { label: "Charge Voltage", value: "58.4 V" },
    { label: "Storage Temperature", value: "0°C to 40°C" },
    { label: "Parallel Expansion", value: "Up to 16 Units" },
    { label: "BMS", value: "Intelligent Smart BMS" },
    { label: "Warranty", value: "5 Years" }
  ],
  "ess-51-2v-314ah": [
    { label: "Model Name", value: "ESS51.2V314AH" },
    { label: "Nominal Voltage", value: "51.2 V" },
    { label: "Nominal Capacity", value: "314 Ah" },
    { label: "Capacity (kWh)", value: "16.08 kWh" },
    { label: "Battery Chemistry", value: "LiFePO4" },
    { label: "Communication", value: "CAN / RS485" },
    { label: "Max Charging Current", value: "100 A" },
    { label: "Cycle Life @ 80% DOD", value: "≥4000 Cycles" },
    { label: "Depth of Discharge", value: "95%" },
    { label: "Continuous Discharge Current", value: "0.5 C (115 A)" },
    { label: "Discharge Current", value: "1 C (314 A, 10 Seconds)" },
    { label: "Charge Voltage", value: "58.4 V" },
    { label: "Storage Temperature", value: "0°C to 40°C" },
    { label: "Scalability", value: "Up to 16 Units in Parallel" },
    { label: "BMS", value: "Intelligent Smart BMS" },
    { label: "Warranty", value: "5 Years" }
  ],
  "ess-96v-50ah": [
    { label: "Model name", value: "ESS96V50AH" },
    { label: "Specification", value: "96V 50AH" },
    { label: "Capacity (kwh)", value: "4.8 KWH" },
    { label: "Battery Chemistry", value: "LiFePO4 (Lithium Iron Phosphate)" },
    { label: "Communication", value: "CAN / RS485" },
    { label: "Max charging current", value: "50 A" },
    { label: "Cycle life", value: "≥4000 Cycles @ 80% DOD" },
    { label: "Depth of Discharge (DOD)", value: "95%" },
    { label: "Charge Voltage", value: "109.5 V" },
    { label: "Discharge Cut-off Voltage", value: "75 V" },
    { label: "Maximum Charging Current", value: "50 A" },
    { label: "Continuous Discharge Current", value: "50 A" },
    { label: "Storage Temperature", value: "0°C to 40°C" },
    { label: "Installation", value: "Floor Standing / Rack Mounted" },
    { label: "Warranty", value: "5 Years" }
  ],
  "ups-120v-series": [
    { label: "Model Name", value: "ESS120V50AH / ESS120V100AH / ESS120V150AH" },
    { label: "Specification", value: "120V 50Ah / 120V 100Ah / 120V 150Ah" },
    { label: "Capacity (kWh)", value: "6.0 kWh / 12.0 kWh / 18.0 kWh" },
    { label: "Battery Chemistry", value: "LiFePO4" },
    { label: "Communication", value: "CAN / RS485" },
    { label: "Max Charging Current", value: "50 A / 100 A / 150 A" },
    { label: "Cycle Life @ 80% DOD", value: "≥4000 Cycles" },
    { label: "Depth of Discharge", value: "95%" },
    { label: "Continue Dis-Current", value: "0.5 C" },
    { label: "Discharge Current", value: "1C (10 Seconds)" },
    { label: "Charge Voltage", value: "136.8 V" },
    { label: "Storage Temperature", value: "0°C to 40°C" },
    { label: "Warranty", value: "5 Years" }
  ],
  "ups-240v-series": [
    { label: "Model Name", value: "ESS240V50AH / ESS240V100AH / ESS240V150AH" },
    { label: "Specification", value: "240V 50Ah / 240V 100Ah / 240V 150Ah" },
    { label: "Capacity (kWh)", value: "12.0 kWh / 24.0 kWh / 36.0 kWh" },
    { label: "Battery Chemistry", value: "LiFePO4" },
    { label: "Communication", value: "CAN / RS485" },
    { label: "Max Charging Current", value: "50 A / 100 A / 150 A" },
    { label: "Cycle Life @ 80% DOD", value: "≥4000 Cycles" },
    { label: "Depth of Discharge", value: "95%" },
    { label: "Continue Dis-Current", value: "0.5 C" },
    { label: "Discharge Current", value: "1C (10 Seconds)" },
    { label: "Charge Voltage", value: "273.6 V" },
    { label: "Storage Temperature", value: "0°C to 40°C" },
    { label: "Warranty", value: "5 Years" }
  ],
  "ups-360v-series": [
    { label: "Model Name", value: "ESS360V50AH / ESS360V100AH / ESS360V150AH" },
    { label: "Specification", value: "360V 50Ah / 360V 100Ah / 360V 150Ah" },
    { label: "Capacity (kWh)", value: "18.0 kWh / 36.0 kWh / 54.0 kWh" },
    { label: "Battery Chemistry", value: "LiFePO4" },
    { label: "Communication", value: "CAN / RS485" },
    { label: "Max Charging Current", value: "50 A / 100 A / 150 A" },
    { label: "Cycle Life @ 80% DOD", value: "≥4000 Cycles" },
    { label: "Depth of Discharge", value: "95%" },
    { label: "Continue Dis-Current", value: "0.5 C" },
    { label: "Discharge Current", value: "1C (10 Seconds)" },
    { label: "Charge Voltage", value: "410.4 V" },
    { label: "Storage Temperature", value: "0°C to 40°C" },
    { label: "Warranty", value: "5 Years" }
  ],
  "ups-480v-series": [
    { label: "Model Name", value: "ESS480V50AH / ESS480V100AH / ESS480V150AH" },
    { label: "Specification", value: "480V 50Ah / 480V 100Ah / 480V 150Ah" },
    { label: "Capacity (kWh)", value: "24.0 kWh / 48.0 kWh / 72.0 kWh" },
    { label: "Battery Chemistry", value: "LiFePO4" },
    { label: "Communication", value: "CAN / RS485" },
    { label: "Max Charging Current", value: "50 A / 100 A / 150 A" },
    { label: "Cycle Life @ 80% DOD", value: "≥4000 Cycles" },
    { label: "Depth of Discharge", value: "95%" },
    { label: "Continue Dis-Current", value: "0.5 C" },
    { label: "Peak Discharge Current", value: "1C (10 Seconds)" },
    { label: "Charge Voltage", value: "547.2 V" },
    { label: "Storage Temperature", value: "0°C to 55°C" },
    { label: "Warranty", value: "5 Years" }
  ],
  "container-160kw-836kwh": [
    { label: "Model Name", value: "Container 160kW/836kWh" },
    { label: "Chemistry", value: "LFP" },
    { label: "Cell Capacity", value: "314Ah" },
    { label: "Rack Capacity", value: "208.8kWh" },
    { label: "BMS Type", value: "Smart" },
    { label: "No of Racks", value: "4" },
    { label: "Rated Capacity", value: "836kWh" },
    { label: "Cooling Type", value: "HVAC" },
    { label: "Cell configuration", value: "1P208S x 4 racks" },
    { label: "Nominal Voltage", value: "665.6V" },
    { label: "Voltage Range", value: "520V - 748V" },
    { label: "Allowed Depth of Discharge", value: "90%" },
    { label: "Approx Weight", value: "2 Tonne each rack" },
    { label: "Operating Temperature", value: "-10 - 50C" },
    { label: "Warranty", value: "5 Years" }
  ]
}
